version: "3"
services:
  api:
    image: vinaykarode/get-client-ip:0.0.1
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"

  web-cli:
    image: vinaykarode/get-client-ip:0.0.1
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
